import type { SavedPost } from "@/app/saved-posts/_types";

export const savedPosts: SavedPost[] = [
  {
    id: "1",
    postType: "Question",
    author: {
      id: "u1",
      name: "Daniel Kim",
      email: "daniel.kim@devmail.com",
      avatar: null,
    },
    handle: "@danielkim",
    time: "1h",
    title: "How are teams versioning shared Zod schemas across services?",
    status: "Reviewing",
    savedDate: "2026-02-20",
    tags: [
      { id: "1", name: "TypeScript" },
      { id: "2", name: "Zod" },
      { id: "3", name: "API Contract" },
      { id: "4", name: "Monorepo" },
    ],
    stats: { helpful: 86, replies: 14, saves: 62 },
  },
  {
    id: "2",
    postType: "Guide",
    author: {
      id: "u2",
      name: "Sophia Martinez",
      email: "sophia.martinez@devmail.com",
      avatar: null,
    },
    handle: "@sophiadev",
    time: "3h",
    title: "Designing pagination that won’t break mobile clients",
    status: "Solved",
    savedDate: "2026-02-18",
    tags: [
      { id: "5", name: "API Design" },
      { id: "6", name: "Pagination" },
      { id: "7", name: "Mobile" },
      { id: "8", name: "Backend" },
    ],
    stats: { helpful: 132, replies: 9, saves: 104 },
  },
  {
    id: "3",
    postType: "RFC",
    author: {
      id: "u3",
      name: "Liam O'Connor",
      email: "liam.oconnor@devmail.com",
      avatar: null,
    },
    handle: "@liamoc",
    time: "8h",
    title: "RFC: Replace cron jobs with durable queue workers",
    status: "Reviewing",
    savedDate: "2026-02-10",
    tags: [
      { id: "9", name: "Architecture" },
      { id: "10", name: "Queues" },
      { id: "11", name: "Infra" },
      { id: "12", name: "Reliability" },
    ],
    stats: { helpful: 58, replies: 27, saves: 41 },
  },
  {
    id: "4",
    postType: "Build Log",
    author: {
      id: "u4",
      name: "Emily Chen",
      email: "emily.chen@devmail.com",
      avatar: null,
    },
    handle: "@emchen",
    time: "1d",
    title: "Build log: reducing CI time by 40% with smart caching",
    status: "Solved",
    savedDate: "2026-01-28",
    tags: [
      { id: "13", name: "CI/CD" },
      { id: "14", name: "GitHub Actions" },
      { id: "15", name: "Caching" },
      { id: "16", name: "DevEx" },
    ],
    stats: { helpful: 97, replies: 11, saves: 88 },
  },
  {
    id: "5",
    postType: "Question",
    author: {
      id: "u5",
      name: "Arjun Patel",
      email: "arjun.patel@devmail.com",
      avatar: null,
    },
    handle: "@arjunbuilds",
    time: "2d",
    title: "What’s your approach to feature flags for web and mobile?",
    status: "Solved",
    savedDate: "2026-02-02",
    tags: [
      { id: "17", name: "Feature Flags" },
      { id: "18", name: "Release" },
      { id: "7", name: "Mobile" },
      { id: "19", name: "Web" },
    ],
    stats: { helpful: 24, replies: 8, saves: 19 },
  },
  {
    id: "6",
    postType: "Guide",
    author: {
      id: "u6",
      name: "Isabella Rossi",
      email: "isabella.rossi@devmail.com",
      avatar: null,
    },
    handle: "@isarossi",
    time: "3d",
    title: "Database migrations without downtime",
    status: "Reviewing",
    savedDate: "2026-02-22",
    tags: [
      { id: "20", name: "Database" },
      { id: "21", name: "Migration" },
      { id: "22", name: "SRE" },
      { id: "23", name: "Backfill" },
    ],
    stats: { helpful: 173, replies: 21, saves: 146 },
  },
  {
    id: "7",
    postType: "RFC",
    author: {
      id: "u7",
      name: "Noah Williams",
      email: "noah.williams@devmail.com",
      avatar: null,
    },
    handle: "@noahcodes",
    time: "5d",
    title: "RFC: Standardize logging fields across services",
    status: "Solved",
    savedDate: "2026-01-15",
    tags: [
      { id: "24", name: "Observability" },
      { id: "25", name: "Logging" },
      { id: "26", name: "Tracing" },
      { id: "27", name: "Standards" },
    ],
    stats: { helpful: 41, replies: 18, saves: 33 },
  },
  {
    id: "8",
    postType: "Build Log",
    author: {
      id: "u8",
      name: "Hannah Müller",
      email: "hannah.mueller@devmail.com",
      avatar: null,
    },
    handle: "@hmuller",
    time: "1w",
    title: "Build log: migrating from CRA to Vite",
    status: "Reviewing",
    savedDate: "2026-02-25",
    tags: [
      { id: "28", name: "React" },
      { id: "29", name: "Vite" },
      { id: "30", name: "Frontend" },
      { id: "31", name: "Tooling" },
    ],
    stats: { helpful: 11, replies: 6, saves: 9 },
  },
  {
    id: "9",
    postType: "Question",
    author: {
      id: "u9",
      name: "Lucas Fernandes",
      email: "lucas.fernandes@devmail.com",
      avatar: null,
    },
    handle: "@lucasdev",
    time: "2w",
    title: "How do you structure large-scale Next.js app folders?",
    status: "Reviewing",
    savedDate: "2026-02-05",
    tags: [
      { id: "32", name: "Next.js" },
      { id: "9", name: "Architecture" },
      { id: "30", name: "Frontend" },
      { id: "33", name: "Scaling" },
    ],
    stats: { helpful: 64, replies: 12, saves: 47 },
  },
  {
    id: "10",
    postType: "Guide",
    author: {
      id: "u10",
      name: "Olivia Johnson",
      email: "olivia.johnson@devmail.com",
      avatar: null,
    },
    handle: "@oliviawritescode",
    time: "3w",
    title: "Practical API error handling patterns",
    status: "Solved",
    savedDate: "2026-01-30",
    tags: [
      { id: "34", name: "API" },
      { id: "35", name: "Error Handling" },
      { id: "36", name: "Distributed Systems" },
      { id: "8", name: "Backend" },
    ],
    stats: { helpful: 205, replies: 34, saves: 189 },
  },
];
